### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/vasilija.joksimovic#1]
Hi @vasilijajoksimovic ,

Please do the following:

1. Write a comment below that you have received this test ticket. 
2. Please tag me using @ then typing my GitHub name.
3. Then close this ticket.

Thanks,
Valentina

**Comment by vasilijajoksimovic** [comment]
I have received the test ticket.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  I've done my task, you can review it !

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  I've noticed that I've made a mistake so I had to do the task again wiht a different name. I just put 2 on Main so the correct one is the Main2.
