### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by vasilijajoksimovic** [alptium/vasilija.joksimovic#2]

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  I've done the task, you can  review it now.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, I cannot see hello-world project

Instructions: https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World
See my repository where there is hello-world https://github.com/alptium/valentina.cupac

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  Can you see it now? I've made a new one...

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, but please from your repository delete the files:
.classpath
.project

Delete these ONLY from vasilija.joksimovic.

**Comment by valentinajemuovic** [comment]
P.S. Because those were the files that were incorrectly created from the first time when you were making hello world...

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  OK, done.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, when fixes are done, please move back to "In review" so that it appears in my list. So whenever you finish fixes, move to "In review" again. Please do that now.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic:
1. Please put Main.java into a package, beause all classes should be placed into a package. See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World step 17. 
2. Please delete "// TODO Auto-generated method stub" because you've added code.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  Redone.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, correct.
