### ISSUE TITLE
Gradebook

### ISSUE THREAD

**Issue by vasilijajoksimovic** [alptium/vasilija.joksimovic#4]

**Comment by vasilijajoksimovic** [comment]
@valentinacupac You can review this task.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac I've noticed a few mistakes, i'll return this task to in progress.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  You can review it now.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic please see the formatting rules in https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World also in several parts I saw style inconsistency.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic,

Ok style is good now.

Next, regarding code:

```
			System.out.printf(studentName1);
			System.out.println("\t");
			System.out.printf(studentSurname1); 
			System.out.println("\t");
			System.out.println("Grade:" + grade1);
			System.out.println("\n");

```
It's correct, but it's very rare to use that style in Java programming.

Please write in this way, this is more common:

```
			System.out.println(studentName1 + "\t" + studentSurname1 + "\t" + "Grade: " + grade1);
			System.out.println();
```

Please check this across all the code base.

Also, re-read the task, how is total grade defined? Is it sum or average? https://github.com/alptium/valentina.cupac/wiki/05.-Gradebook

There is also one spelling mistake, please fix.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  I redone it this way.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, the spelling mistake was not fixed: treir

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  I'havent noticed it at all. Changed.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, please also check why there is still "\\n", also you forgot to replace some of the printf.

Also are the brackets necessary here?

`double totalGrade = (grade1 + grade2 + grade3 + grade4 + grade5);`

**Comment by valentinajemuovic** [comment]
P.S. Please review again whole code and test just to ensure it's all cleaned up.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  I left printf because at first, somehow  the eclipse didn't want to accept the println but after it was ok.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic:
1. I still see some printf.
2. See 14 here https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World

**Comment by vasilijajoksimovic** [comment]
@valentinacupac

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, correct.
