### ISSUE TITLE
Elite Sports Team Selector (OOP)

### ISSUE THREAD

**Issue by vasilijajoksimovic** [alptium/vasilija.joksimovic#8]

**Comment by vasilijajoksimovic** [comment]
@valentinacupac 
Attributes: name, surname,age...

Constructor : public Candidate(String name, String surname, int age, int height, int weight, boolean healthProblems, boolean earlierInjuries )

Methods: public String getName(), public String getSurname()...

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, based on task instructions, please refactor your existing project elite-sports-team-selector instead of creating the new one.

**Comment by vasilijajoksimovic** [comment]
@valentinacupac  You can review the task.

**Comment by valentinajemuovic** [comment]
@vasilijajoksimovic, please review the formatting fixes I had committed.

Aside from that, the task is fine, closing this ticket.
